name = input("Digite o nome do filme:\n")
yearLaunch = int(input("Digite o ano de lançamento do filme:\n"))
noteMovie = float(input("Digite a nota do filme:\n"))
print(name)
print(yearLaunch)
print(noteMovie)
print(type(name))
print(type(yearLaunch))
print(type(noteMovie))